# Generated by Django 6.0.2 on 2026-02-26 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ποσό')),
                ('currency', models.CharField(default='eur', max_length=3)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Αναμονή'), ('succeeded', 'Επιτυχής'), ('failed', 'Αποτυχία'), ('refunded', 'Επιστροφή'), ('partially_refunded', 'Μερική Επιστροφή')], default='pending', max_length=30)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Πληρωμή',
                'verbose_name_plural': 'Πληρωμές',
                'ordering': ['-created_at'],
            },
        ),
    ]
