# Generated by Django 6.0.2 on 2026-02-26 20:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Επωνυμία')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Slug')),
                ('category', models.CharField(choices=[('health', 'Υγεία & Ιατρική'), ('beauty', 'Ομορφιά & Κομμωτική'), ('fitness', 'Fitness & Γυμναστήριο'), ('education', 'Εκπαίδευση & Φροντιστήρια'), ('legal', 'Νομικές Υπηρεσίες'), ('accounting', 'Λογιστικές Υπηρεσίες'), ('auto', 'Αυτοκίνητο & Συνεργείο'), ('tech', 'Τεχνολογία & IT'), ('other', 'Άλλο')], default='other', max_length=50, verbose_name='Κατηγορία')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Διεύθυνση')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('auto_confirm', models.BooleanField(default=True, help_text='Αν είναι OFF, κάθε ραντεβού χρειάζεται χειροκίνητη έγκριση.', verbose_name='Αυτόματη επιβεβαίωση')),
                ('requires_deposit', models.BooleanField(default=False, verbose_name='Απαιτεί προκαταβολή')),
                ('deposit_percentage', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Ποσοστό προκαταβολής (%)')),
                ('stripe_account_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Επιχείρηση',
                'verbose_name_plural': 'Επιχειρήσεις',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ονοματεπώνυμο')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Ειδικότητα / Ρόλος')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='businesses.business')),
                ('user', models.OneToOneField(blank=True, help_text='Προαιρετικά: σύνδεση με sub-account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Υπάλληλος',
                'verbose_name_plural': 'Υπάλληλοι',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Υπηρεσία')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Διάρκεια (λεπτά)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Τιμή (€)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Υπηρεσία',
                'verbose_name_plural': 'Υπηρεσίες',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Λόγος')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='businesses.employee')),
            ],
            options={
                'verbose_name': 'Ειδική Αργία',
                'verbose_name_plural': 'Ειδικές Αργίες',
                'ordering': ['date'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Δευτέρα'), (1, 'Τρίτη'), (2, 'Τετάρτη'), (3, 'Πέμπτη'), (4, 'Παρασκευή'), (5, 'Σάββατο'), (6, 'Κυριακή')], verbose_name='Ημέρα')),
                ('start_time', models.TimeField(verbose_name='Ώρα Έναρξης')),
                ('end_time', models.TimeField(verbose_name='Ώρα Λήξης')),
                ('is_day_off', models.BooleanField(default=False, verbose_name='Ρεπό')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='businesses.employee')),
            ],
            options={
                'verbose_name': 'Ωράριο Εργασίας',
                'verbose_name_plural': 'Ωράρια Εργασίας',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('employee', 'day_of_week')},
            },
        ),
    ]
