# Generated by Django 6.0.2 on 2026-02-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='allow_employee_selection',
            field=models.BooleanField(default=True, help_text='Επιτρέπει στους πελάτες να επιλέξουν συγκεκριμένο υπάλληλο.', verbose_name='Επιλογή υπαλλήλου'),
        ),
    ]
