# Generated by Django 6.0.2 on 2026-02-26 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_allow_employee_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='default_end_time',
            field=models.TimeField(default='17:00', help_text='Προεπιλεγμένη ώρα λήξης εργασίας', verbose_name='Ώρα λήξης (προεπιλογή)'),
        ),
        migrations.AddField(
            model_name='business',
            name='default_start_time',
            field=models.TimeField(default='09:00', help_text='Προεπιλεγμένη ώρα έναρξης εργασίας', verbose_name='Ώρα έναρξης (προεπιλογή)'),
        ),
        migrations.AddField(
            model_name='business',
            name='hourly_capacity',
            field=models.PositiveIntegerField(default=1, help_text='Πόσα ραντεβού μπορείτε να εξυπηρετήσετε ταυτόχρονα (χρήσιμο αν δεν έχετε καταχωρημένους υπαλλήλους).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Χωρητικότητα ανά ώρα'),
        ),
    ]
