# Generated by Django 6.0.2 on 2026-02-27 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_default_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cancellation_fee_percentage',
            field=models.PositiveIntegerField(default=30, help_text='Το ποσοστό που θα κρατηθεί σε περίπτωση ακύρωσης (π.χ. 30% = επιστροφή 70%).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ποσοστό χρέωσης ακύρωσης (%)'),
        ),
        migrations.AddField(
            model_name='business',
            name='charge_cancellation_fee',
            field=models.BooleanField(default=False, help_text='Αν είναι ενεργό, κρατείται ποσοστό σε περίπτωση ακύρωσης από τον πελάτη.', verbose_name='Χρέωση ακύρωσης'),
        ),
    ]
