# Generated by Django 6.0.2 on 2026-03-04 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_cancellation_fee_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Δευτέρα'), (1, 'Τρίτη'), (2, 'Τετάρτη'), (3, 'Πέμπτη'), (4, 'Παρασκευή'), (5, 'Σάββατο'), (6, 'Κυριακή')], verbose_name='Ημέρα')),
                ('start_time', models.TimeField(default='09:00', verbose_name='Ώρα Έναρξης')),
                ('end_time', models.TimeField(default='17:00', verbose_name='Ώρα Λήξης')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Κλειστό')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Ωράριο Επιχείρησης',
                'verbose_name_plural': 'Ωράρια Επιχείρησης',
                'ordering': ['day_of_week'],
                'unique_together': {('business', 'day_of_week')},
            },
        ),
    ]
