# Generated by Django 6.0.2 on 2026-03-04 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_businesshours'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ημερομηνία Κλεισίματος')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Λόγος')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Κλείσιμο Επιχείρησης',
                'verbose_name_plural': 'Κλεισίματα Επιχείρησης',
                'ordering': ['date'],
                'unique_together': {('business', 'date')},
            },
        ),
    ]
