# Generated by Django 5.1.15 on 2026-03-08 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_businessdayoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Διάρκεια (λεπτά)'),
        ),
    ]
