# Generated by Django 5.1.2 on 2026-03-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_fix_invalid_service_durations'),
        ('businesses', '0009_business_custom_category_bilingual'),
    ]

    operations = [
    ]
