# Generated by Django 5.1.2 on 2026-03-29 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_merge_20260329_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='allow_employee_accounts',
            field=models.BooleanField(default=False, help_text='Επιτρέπει στους υπαλλήλους να δημιουργήσουν λογαριασμό και να διαχειρίζονται τη διαθεσιμότητά τους.', verbose_name='Λογαριασμοί Υπαλλήλων'),
        ),
        migrations.CreateModel(
            name='EmployeeInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Πρόσκλησης')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='businesses.employee')),
            ],
            options={
                'verbose_name': 'Πρόσκληση Υπαλλήλου',
                'verbose_name_plural': 'Προσκλήσεις Υπαλλήλων',
                'ordering': ['-created_at'],
            },
        ),
    ]
