# Generated by Django 5.1.2 on 2026-03-29 16:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0011_business_allow_employee_accounts_employeeinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialdayoff',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Αίτημα Άδειας', 'verbose_name_plural': 'Αιτήματα Αδειών'},
        ),
        migrations.AddField(
            model_name='specialdayoff',
            name='admin_response',
            field=models.TextField(blank=True, help_text='Σημειώσεις από τον εργοδότη', verbose_name='Απάντηση Διαχειριστή'),
        ),
        migrations.AddField(
            model_name='specialdayoff',
            name='request_notes',
            field=models.TextField(blank=True, help_text='Πρόσθετες πληροφορίες από τον υπάλληλο', verbose_name='Σημειώσεις Αιτήματος'),
        ),
        migrations.AddField(
            model_name='specialdayoff',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Αιτήματος'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialdayoff',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Αξιολόγησης'),
        ),
        migrations.AddField(
            model_name='specialdayoff',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Αξιολογήθηκε από'),
        ),
        migrations.AddField(
            model_name='specialdayoff',
            name='status',
            field=models.CharField(choices=[('pending', 'Αναμονή'), ('approved', 'Εγκρίθηκε'), ('rejected', 'Απορρίφθηκε')], default='pending', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.CreateModel(
            name='AbsenceRequestChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Μήνυμα')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία')),
                ('is_read', models.BooleanField(default=False, verbose_name='Αναγνώστηκε')),
                ('absence_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='businesses.specialdayoff', verbose_name='Αίτημα Άδειας')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Αποστολέας')),
            ],
            options={
                'verbose_name': 'Μήνυμα Αιτήματος',
                'verbose_name_plural': 'Μηνύματα Αιτημάτων',
                'ordering': ['created_at'],
            },
        ),
    ]
