# Generated by Django 5.1.2 on 2026-04-01 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_alter_specialdayoff_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Τηλέφωνο')], max_length=10, verbose_name='Τύπος Επαφής')),
                ('value', models.CharField(max_length=100, verbose_name='Τιμή (Email ή Τηλέφωνο)')),
                ('label', models.CharField(blank=True, help_text='π.χ. "Ιδιοκτήτης", "Υπεύθυνος", κ.λπ.', max_length=50, verbose_name='Ετικέτα')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_contacts', to='businesses.business', verbose_name='Επιχείρηση')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Επαφή Ειδοποιήσεων',
                'verbose_name_plural': 'Επαφές Ειδοποιήσεων',
                'ordering': ['contact_type', 'label', 'value'],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationcontact',
            constraint=models.CheckConstraint(check=models.Q(('business__isnull', False), ('user__isnull', False), _connector='OR'), name='notification_contact_has_owner'),
        ),
        migrations.AddConstraint(
            model_name='notificationcontact',
            constraint=models.CheckConstraint(check=models.Q(('business__isnull', False), ('user__isnull', False), _connector='AND', _negated=True), name='notification_contact_single_owner'),
        ),
    ]