# Generated by Django 5.1.2 on 2026-04-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0023_business_booking_gap_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialdayoff',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Αίτημα Άδειας', 'verbose_name_plural': 'Αιτήματα Αδειών'},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('business', 'name')},
        ),
    ]
