# Generated by Django 5.1.2 on 2026-04-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0024_alter_specialdayoff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='allow_employee_booking_actions',
            field=models.BooleanField(default=True, help_text='Επιτρέπει στους υπαλλήλους να επιβεβαιώνουν ή να απορρίπτουν τα ραντεβού που τους έχουν ανατεθεί.', verbose_name='Ενέργειες Ραντεβού από Υπαλλήλους'),
        ),
    ]
