# Generated by Django 5.1.2 on 2026-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0025_business_allow_employee_booking_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_calendar_id',
            field=models.CharField(blank=True, default='primary', help_text='Προεπιλογή: primary', max_length=255, verbose_name='Google Calendar ID'),
        ),
        migrations.AddField(
            model_name='business',
            name='google_calendar_refresh_token',
            field=models.TextField(blank=True, verbose_name='Google OAuth Refresh Token'),
        ),
        migrations.AddField(
            model_name='business',
            name='google_calendar_sync_enabled',
            field=models.BooleanField(default=False, help_text='Συγχρονισμός ραντεβού με Google Calendar.', verbose_name='Google Calendar Sync'),
        ),
        migrations.AddField(
            model_name='business',
            name='google_calendar_token_uri',
            field=models.CharField(blank=True, default='https://oauth2.googleapis.com/token', max_length=255),
        ),
    ]
