# Generated by Django 5.1.2 on 2026-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0028_businesscustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='auto_reply_enabled',
            field=models.BooleanField(default=False, help_text='Ενεργοποιήστε για αυτόματη απάντηση σε όλες τις κριτικές με το προεπιλεγμένο μήνυμα.', verbose_name='Αυτόματη απάντηση σε κριτικές'),
        ),
        migrations.AddField(
            model_name='business',
            name='auto_reply_template',
            field=models.TextField(default='Σας ευχαριστούμε πολύ για την αξιολόγηση και τα σχόλιά σας.\n\nΗ ομάδα μας εκτιμά τη στήριξή σας.', help_text='Το μήνυμα που θα αποστέλλεται αυτόματα σε κάθε κριτική.', verbose_name='Πρόσχεδιο αυτόματης απάντησης'),
        ),
    ]
