# Generated by Django 5.1.2 on 2026-04-10 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0029_business_auto_reply_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Προαιρετικά: σύνδεση με sub-account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('business', 'user'), name='unique_employee_user_per_business'),
        ),
    ]
