# Generated by Django 5.1.2 on 2026-04-10 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0030_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cancellation_deadline_hours',
            field=models.PositiveIntegerField(default=24, help_text='Πόσες ώρες πριν το ραντεβού επιτρέπεται ακύρωση/επαναπρογραμματισμός.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(720)], verbose_name='Προθεσμία ακύρωσης (ώρες πριν)'),
        ),
    ]
