# Generated by Django 5.1.2 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0031_service_cancellation_deadline_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='public_site_mode',
            field=models.CharField(choices=[('booking_page', 'Σελίδα κρατήσεων'), ('custom_html', 'Προσαρμοσμένη HTML σελίδα'), ('built_in_site', 'Προκατασκευασμένη δημόσια σελίδα'), ('external_website', 'Εξωτερικό website')], default='booking_page', help_text='Επιλέξτε τι θα ανοίγει όταν κάποιος επισκέπτεται το δημόσιο link της επιχείρησης.', max_length=20, verbose_name='Τρόπος δημόσιας σελίδας'),
        ),
        migrations.AddField(
            model_name='business',
            name='external_website_url',
            field=models.URLField(blank=True, help_text='Προαιρετικός σύνδεσμος προς το δικό σας website.', verbose_name='Εξωτερικό website'),
        ),
    ]
