# Generated by Django 5.1.2 on 2026-03-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('professional', 'Επαγγελματίας'), ('customer', 'Πελάτης'), ('employee', 'Υπάλληλος')], default='customer', max_length=20),
        ),
    ]
