# Generated by Django 5.1.2 on 2026-04-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_phone_otp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_seen_welcome_flow',
            field=models.BooleanField(default=False, help_text='Whether the user has completed or skipped the first-time welcome flow.', verbose_name='Seen Welcome Flow'),
        ),
    ]
