# Generated by Django 5.1.15 on 2026-03-09 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_price_at_booking'),
        ('businesses', '0007_min_duration_5'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('missed_appointment', 'Δεν τήρησε το ραντεβού'), ('offensive_language', 'Προσβλητική γλώσσα'), ('no_show_business', 'Επιχείρηση δεν εμφανίστηκε'), ('poor_service', 'Κακή εξυπηρέτηση'), ('fraud', 'Απάτη / Παραπλάνηση'), ('other', 'Άλλο')], max_length=40, verbose_name='Κατηγορία')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('status', models.CharField(choices=[('new', 'Νέα'), ('under_review', 'Υπό εξέταση'), ('resolved', 'Επιλύθηκε'), ('dismissed', 'Απορρίφθηκε')], default='new', max_length=20, verbose_name='Κατάσταση')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Σημειώσεις Διαχειριστή')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='bookings.booking', verbose_name='Σχετικό Ραντεβού')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='businesses.business', verbose_name='Επιχείρηση')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='Αναφέρων')),
            ],
            options={
                'verbose_name': 'Αναφορά',
                'verbose_name_plural': 'Αναφορές',
                'ordering': ['-created_at'],
            },
        ),
    ]
