# Generated by Django 6.0.2 on 2026-02-26 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('start_time', models.TimeField(verbose_name='Ώρα Έναρξης')),
                ('end_time', models.TimeField(verbose_name='Ώρα Λήξης')),
                ('status', models.CharField(choices=[('pending', 'Σε αναμονή'), ('confirmed', 'Επιβεβαιωμένο'), ('cancelled', 'Ακυρωμένο'), ('completed', 'Ολοκληρωμένο'), ('no_show', 'No-Show')], default='pending', max_length=20, verbose_name='Κατάσταση')),
                ('payment_status', models.CharField(choices=[('not_required', 'Δεν απαιτείται'), ('pending', 'Αναμονή πληρωμής'), ('paid', 'Πληρωμένο'), ('refunded', 'Επιστροφή'), ('partially_refunded', 'Μερική επιστροφή')], default='not_required', max_length=30, verbose_name='Κατάσταση Πληρωμής')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ποσό Προκαταβολής')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('review_invite_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='businesses.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='businesses.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='businesses.service')),
            ],
            options={
                'verbose_name': 'Ραντεβού',
                'verbose_name_plural': 'Ραντεβού',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='bookings.booking')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
