# Generated by Django 5.1.15 on 2026-03-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_guest_name_booking_guest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_at_booking',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Τιμή Κατά την Κράτηση'),
        ),
    ]
