# Generated by Django 5.1.15 on 2026-03-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_price_at_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='not_required', max_length=30, verbose_name='Κατάσταση Πληρωμής'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No-Show')], default='pending', max_length=20, verbose_name='Κατάσταση'),
        ),
    ]
