# Generated by Django 5.1.15 on 2026-03-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_payment_status_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_access_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Κωδικός Πρόσβασης Επισκέπτη'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Επισκέπτη'),
        ),
    ]
