# Generated by Django 5.1.15 on 2026-03-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_guest_access_token_booking_guest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_contact_preference',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Telephone'), ('both', 'Both')], default='both', max_length=10, verbose_name='Προτίμηση Επικοινωνίας'),
        ),
    ]
