# Generated by Django 5.1.15 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_guest_contact_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Λόγος Απόρριψης'),
        ),
    ]
