# Generated by Django 5.1.2 on 2026-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
