# Generated by Django 6.0.2 on 2026-02-26 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=15, verbose_name='Τηλέφωνο')),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(verbose_name='Μήνυμα')),
                ('sms_type', models.CharField(choices=[('confirmation', 'Επιβεβαίωση ραντεβού'), ('reminder', 'Υπενθύμιση 24ωρο'), ('review_invite', 'Πρόσκληση αξιολόγησης'), ('cancellation', 'Ακύρωση ραντεβού'), ('approved', 'Εγκρίθηκε ραντεβού'), ('rejected', 'Απορρίφθηκε ραντεβού'), ('new_booking', 'Νέο ραντεβού (προς επαγγελματία)')], max_length=20, verbose_name='Τύπος')),
                ('status', models.CharField(choices=[('pending', 'Αναμονή'), ('sent', 'Εστάλη'), ('failed', 'Αποτυχία')], default='pending', max_length=10)),
                ('twilio_sid', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'SMS Ειδοποίηση',
                'verbose_name_plural': 'SMS Ειδοποιήσεις',
                'ordering': ['-created_at'],
            },
        ),
    ]
