# Generated by Django 5.1.2 on 2026-04-02 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_gr', models.CharField(max_length=200, verbose_name='Τίτλος (Ελληνικά)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('description_gr', models.TextField(verbose_name='Περιγραφή (Ελληνικά)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('content_gr', models.TextField(blank=True, verbose_name='Περιεχόμενο (Ελληνικά)')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (English)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Εικόνα')),
                ('status', models.CharField(choices=[('draft', 'Σχέδιο'), ('published', 'Δημοσιευμένο')], default='draft', max_length=20, verbose_name='Κατάσταση')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Δημοσιεύθηκε')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_created', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Ειδήσεις',
                'verbose_name_plural': 'Ειδήσεις',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at'], name='notificatio_publish_d18321_idx'), models.Index(fields=['status'], name='notificatio_status_4156b1_idx')],
            },
        ),
    ]
